M48
; DRILL file {KiCad 9.0.0} date 2025-05-04T18:28:28+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-05-04T18:28:28+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0453
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.1063
%
G90
G05
T1
X6.2478Y-2.9382
X6.2478Y-3.1657
T2
X5.5512Y-3.3258
T3
X4.7638Y-3.3258
T4
X4.5276Y-2.8435
X4.5276Y-4.7333
X5.8268Y-2.8435
X5.8268Y-4.7333
M30
